#!/usr/bin/env bash
# command to be used to insall on the web server

sudo apt-get update
sudo apt-get install nginx
sudo ufw 'Nginx HTTP'

echo "Hello World!" | sudo tee /var/www/html/index.html

# testing nginx config.
sudo nginx -t

sudo service nginx reload
